name: test-on-push

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.4"
    - name: Install poetry ${{ matrix.poetry-version }}
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==1.3.1

    - name: Install palpy dependencies
      run: |
        python -m pip install numpy==1.24.0 cython==0.29.32 
        python -m pip install palpy==1.8.1
        python -m poetry add palpy==1.8.1s
        
    - name: View poetry --help
      run: poetry --help

    - name: Install dependencies
      shell: bash
      run: python -m poetry install

    - name: Test with pytest
      run: |
       python3 -m poetry run pytest --cov
